apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-0
  namespace: middleware
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/datadir-galera-0/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-1
  namespace: middleware
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/datadir-galera-1/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-galera-2
  namespace: middleware
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/datadir-galera-2/
